// AUTO-GENERATED by scripts/md-to-patient.mjs --walk — 勿手改（源：剧本 v3 markdown）
import { describe, it, expect } from "vitest";
import { patient } from "./patients/qi_yehang";
import { walkScenario, PICKS } from "../engine/walk";

describe("齐夜航 剧本走线验证（长剧本）", () => {
  it("共情线 → cure，trust 达锚点末位 88，轮数 ≥ 100", () => {
    const r = walkScenario(patient, PICKS.empathy);
    expect(r.ending).toBe("cure");
    expect(r.trust).toBe(88);
    expect(r.rounds).toBeGreaterThanOrEqual(100);
  });
  it("均衡线 → cure，碎片触发 ≥ 3", () => {
    const r = walkScenario(patient, PICKS.balanced);
    expect(r.ending).toBe("cure");
    expect(r.memories.length).toBeGreaterThanOrEqual(3);
  });
  it("失误线 → worsen，trust ≤ 70（恶化入口可见）", () => {
    const r = walkScenario(patient, PICKS.mistake);
    expect(r.ending).toBe("worsen");
    expect(r.trust).toBeLessThanOrEqual(70);
  });
  it("探问线 → cure，truth 冲顶 ≥ 100", () => {
    const r = walkScenario(patient, PICKS.probe);
    expect(r.ending).toBe("cure");
    expect(r.truth).toBeGreaterThanOrEqual(100);
  });
});
