// AUTO-GENERATED by scripts/md-to-patient.mjs --walk — 勿手改（源：剧本 v3 markdown）
import { describe, it, expect } from "vitest";
import { patient } from "./patients/tang_jianguo";
import { walkScenario, PICKS } from "../engine/walk";

describe("唐建国 剧本走线验证（中剧本）", () => {
  it("共情线 → cure，trust 达锚点末位 70，轮数 ≥ 70", () => {
    const r = walkScenario(patient, PICKS.empathy);
    expect(r.ending).toBe("cure");
    expect(r.trust).toBe(70);
    expect(r.rounds).toBeGreaterThanOrEqual(70);
  });
  it("均衡线 → cure，碎片触发 ≥ 2", () => {
    const r = walkScenario(patient, PICKS.balanced);
    expect(r.ending).toBe("cure");
    expect(r.memories.length).toBeGreaterThanOrEqual(2);
  });
  it("失误线 → worsen，trust ≤ 55（恶化入口可见）", () => {
    const r = walkScenario(patient, PICKS.mistake);
    expect(r.ending).toBe("worsen");
    expect(r.trust).toBeLessThanOrEqual(55);
  });
  it("探问线 → cure，truth 冲顶 ≥ 70", () => {
    const r = walkScenario(patient, PICKS.probe);
    expect(r.ending).toBe("cure");
    expect(r.truth).toBeGreaterThanOrEqual(70);
  });
});
