// AUTO-GENERATED by scripts/md-to-patient.mjs --walk — 勿手改（源：剧本 v3 markdown）
import { describe, it, expect } from "vitest";
import { patient } from "./patients/xue_fen";
import { walkScenario, PICKS } from "../engine/walk";

describe("薛芬 剧本走线验证（短剧本）", () => {
  it("共情线 → cure，trust 达锚点末位 58，轮数 ≥ 40", () => {
    const r = walkScenario(patient, PICKS.empathy);
    expect(r.ending).toBe("cure");
    expect(r.trust).toBe(58);
    expect(r.rounds).toBeGreaterThanOrEqual(40);
  });
  it("均衡线 → cure，碎片触发 ≥ 1", () => {
    const r = walkScenario(patient, PICKS.balanced);
    expect(r.ending).toBe("cure");
    expect(r.memories.length).toBeGreaterThanOrEqual(1);
  });
  it("失误线 → worsen，trust ≤ 40（恶化入口可见）", () => {
    const r = walkScenario(patient, PICKS.mistake);
    expect(r.ending).toBe("worsen");
    expect(r.trust).toBeLessThanOrEqual(40);
  });
  it("探问线 → cure，truth 冲顶 ≥ 40", () => {
    const r = walkScenario(patient, PICKS.probe);
    expect(r.ending).toBe("cure");
    expect(r.truth).toBeGreaterThanOrEqual(40);
  });
});
