// AUTO-GENERATED by scripts/scan-patients.mjs — 勿手改
// 源：lib/data/patients/ 下所有患者剧本文件（新增剧本放入即自动进池）
// 重新生成：`npm run dev` / `npm test` / `npm run build`（predev / pretest / prebuild 钩子）
import type { PatientScenario } from "../../types";

/** 判定一个模块导出值是否为患者剧本（导出名不统一：patient / patientA / patientG…） */
function isPatientScenario(x: unknown): x is PatientScenario {
  if (!x || typeof x !== "object") return false;
  const p = x as Partial<PatientScenario>;
  return (
    typeof p.id === "string" &&
    typeof p.startNode === "string" &&
    !!p.dialogues
  );
}

import * as m_chen_mo from "./chen_mo";
import * as m_he_jinglan from "./he_jinglan";
import * as m_jiang_yu from "./jiang_yu";
import * as m_lin_chen from "./lin_chen";
import * as m_lin_xiao from "./lin_xiao";
import * as m_lu_yunxin from "./lu_yunxin";
import * as m_mu_qing from "./mu_qing";
import * as m_su_nian from "./su_nian";
import * as m_tang_zhiyuan from "./tang_zhiyuan";
import * as m_xiao_bei from "./xiao_bei";
import * as m_zhao_haifeng from "./zhao_haifeng";
import * as m_zhao_lei from "./zhao_lei";

const modules: Record<string, unknown> = {
  chen_mo: m_chen_mo,
  he_jinglan: m_he_jinglan,
  jiang_yu: m_jiang_yu,
  lin_chen: m_lin_chen,
  lin_xiao: m_lin_xiao,
  lu_yunxin: m_lu_yunxin,
  mu_qing: m_mu_qing,
  su_nian: m_su_nian,
  tang_zhiyuan: m_tang_zhiyuan,
  xiao_bei: m_xiao_bei,
  zhao_haifeng: m_zhao_haifeng,
  zhao_lei: m_zhao_lei,
};

export const collected: PatientScenario[] = Object.values(modules)
  .flatMap((m) => Object.values(m as Record<string, unknown>))
  .filter(isPatientScenario);
